module.exports = {
	"routerUrls": [{
		"reqUrl": "/nodejs/httpTest",
		"resUrl": "./routes-web/httpTest"
	}, {
		"reqUrl": "/nodejs/fileList",
		"resUrl": "./routes-web/fileList"
	}, {
		"reqUrl": "/nodejs/login",
		"resUrl": "./routes-web/login"
	}, {
		"reqUrl": "/nodejs/userList",
		"resUrl": "./routes-web/userList"
	}, {
		"reqUrl": "/nodejs/recordList",
		"resUrl": "./routes-web/recordList"
	}, {
		"reqUrl": "/nodejs/roleClass",
		"resUrl": "./routes-web/roleClass"
	}, {
		"reqUrl": "/nodejs/productList",
		"resUrl": "./routes-web/productList"
	}, {
		"reqUrl": "/nodejs/productClass",
		"resUrl": "./routes-web/productClass"
	}, {
		"reqUrl": "/nodejs/colorClass",
		"resUrl": "./routes-web/colorClass"
	}, {
		"reqUrl": "/nodejs/optionClass",
		"resUrl": "./routes-web/optionClass"
	}, {
		"reqUrl": "/nodejs/accessoriesClass",
		"resUrl": "./routes-web/accessoriesClass"
	}, {
		"reqUrl": "/nodejs/modelClass",
		"resUrl": "./routes-web/modelClass"
	}, {
		"reqUrl": "/nodejs/braceClass",
		"resUrl": "./routes-web/braceClass"
	}, {
		"reqUrl": "/nodejs/billingList",
		"resUrl": "./routes-web/billingList"
	}, {
		"reqUrl": "/nodejs/shippingList",
		"resUrl": "./routes-web/shippingList"
	}, {
		"reqUrl": "/nodejs/productList",
		"resUrl": "./routes-web/productList"
	}, {
		"reqUrl": "/nodejs/rolePermissionList",
		"resUrl": "./routes-web/rolePermissionList"
	}, {
		"reqUrl": "/nodejs/braceDataList",
		"resUrl": "./routes-web/braceDataList"
	}, {
		"reqUrl": "/nodejs/optionsValueClass",
		"resUrl": "./routes-web/optionsValueClass"
	}, {
		"reqUrl": "/nodejs/optionValueRelationship",
		"resUrl": "./routes-web/optionValueRelationship"
	}, {
		"reqUrl": "/nodejs/accessoriesValueRelationship",
		"resUrl": "./routes-web/accessoriesValueRelationship"
	}, {
		"reqUrl": "/nodejs/orderList",
		"resUrl": "./routes-web/orderList"
	}, {
		"reqUrl": "/nodejs/orderSubmitList",
		"resUrl": "./routes-web/orderSubmitList"
	}]
}